# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2bf8c8f7b9e1a0c1922de2268975606e"
name = "Ninja QR Code"
handle = "ninja-qr-code"
application_url = "https://fee-afterwards-criminal-interfaces.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nfang.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_products"

[auth]
redirect_urls = [
  "https://fee-afterwards-criminal-interfaces.trycloudflare.com/auth/callback",
  "https://fee-afterwards-criminal-interfaces.trycloudflare.com/auth/shopify/callback",
  "https://fee-afterwards-criminal-interfaces.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
